# a=10
# b=2

# try:
#     res=a//b
# except Exception as msg:
#     print(msg)
# else:
#     print(res)    
# finally:
#     print('Program completed')        
import os

print(os.name)